db:
  host: localhost
  username: root
  password: Timmy@870728

redis:
  host: redis-service_redis
  password: 1234

zookeeper:
  host: zookeeper-cluster_zookeeper-node-1:2181?backup=zookeeper-cluster_zookeeper-node-2:2182,zookeeper-cluster_zookeeper-node-3:2183