# Tomcat socket number
server:
  port: 81
#Spring setting
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${db.host}:3306/health?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=UTF-8
      username: ${db.username}
      password: ${db.password}
    hikari:
      read-only:
  redis:
    password: ${redis.password}
    host: ${redis.host}
    port: 6379
    client-type: lettuce
    connect-timeout: 30000
    lettuce:
      pool:
        enabled: true
  task:
    scheduling:
      pool:
        size: 1
      shutdown:
        await-termination: false
        await-termination-period: 10s
  mail:
    host: smtp.gmail.com
    username: examyou076@gmail.com
    password: xpzq adqd ifxc fhgz
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000
        debug: true
    port: 587
  profiles:
    active: test
#dubbo setting
dubbo:
  application:
    name: health_provider
  registry:
    address: zookeeper://${zookeeper.host}
  config-center:
    timeout: 25000
  provider:
    timeout: 30000
  scan:
    base-packages: com.timmy.health.service.impl
#MyBatisPlus setting
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  mapper-locations: classpath*:com/timmy/health/mapper/*.xml
  global-config:
    db-config:
      table-prefix: t_
      id-type: auto
    banner: off
  type-aliases-package: com.timmy.health.domain

