# Tomcat socket number
server:
  port: 81
#Spring setting
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/health?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: timmy072869
  redis:
    password: timmy0728
    host: 192.168.37.133
    port: 6379
    client-type: lettuce
    connect-timeout: 30000
    lettuce:
      pool:
        enabled: true
  task:
    scheduling:
      pool:
        size: 1
      shutdown:
        await-termination: false
        await-termination-period: 10s
#dubbo setting
dubbo:
  application:
    name: health_provider
  registry:
    address: zookeeper://192.168.37.133
    port: 2181
  config-center:
    timeout: 25000
  scan:
    base-packages: com.timmy.health.service.impl
#MyBatisPlus setting
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  mapper-locations: classpath*:com/timmy/health/mapper/*.xml
  global-config:
    db-config:
      table-prefix: t_
      id-type: auto
    banner: off
  type-aliases-package: com.timmy.health.domain
