db:
  host: 104.199.166.238
  username: root
  password: Timmy@870728

redis:
  host: redis-service
  password: 1234

zookeeper:
  host: zookeeper-node-1:2181?backup=zookeeper-node-2:2182,zookeeper-node-3:2183