package com.timmy.health.constant;

/**
 * 消息常數
 */
public class MessageConstant {
    public static final String DELETE_CHECKITEM_FAIL = "刪除檢查項失敗";
    public static final String DELETE_CHECKITEM_SUCCESS = "刪除檢查項成功";
    public static final String ADD_CHECKITEM_SUCCESS = "新增檢查項成功";
    public static final String ADD_CHECKITEM_FAIL = "新增檢查項失敗";
    public static final String EDIT_CHECKITEM_FAIL = "編輯檢查項失敗";
    public static final String EDIT_CHECKITEM_SUCCESS = "編輯檢查項成功";
    public static final String QUERY_CHECKITEM_SUCCESS = "查詢檢查項成功";
    public static final String QUERY_CHECKITEM_FAIL = "查詢檢查項失敗";
    public static final String ADD_CHECKGROUP_FAIL = "新增檢查組失敗";
    public static final String ADD_CHECKGROUP_SUCCESS = "新增檢查組成功";
    public static final String DELETE_CHECKGROUP_FAIL = "刪除檢查組失敗";
    public static final String DELETE_CHECKGROUP_SUCCESS = "刪除檢查組成功";
    public static final String QUERY_CHECKGROUP_SUCCESS = "查詢檢查組成功";
    public static final String QUERY_CHECKGROUP_FAIL = "查詢檢查組失敗";
    public static final String EDIT_CHECKGROUP_FAIL = "編輯檢查組失敗";
    public static final String EDIT_CHECKGROUP_SUCCESS = "編輯檢查組成功";
    public static final String PIC_UPLOAD_SUCCESS = "圖片上傳成功";
    public static final String PIC_UPLOAD_FAIL = "圖片上傳失敗";
    public static final String ADD_SETMEAL_FAIL = "新增套餐失敗";
    public static final String ADD_SETMEAL_SUCCESS = "新增套餐成功";
    public static final String IMPORT_ORDERSETTING_FAIL = "批量導入預約設置數據失敗";
    public static final String IMPORT_ORDERSETTING_SUCCESS = "批量導入預約設置數據成功";
    public static final String ORDERSETTING_SUCCESS = "預約設置成功";
    public static final String ORDERSETTING_FAIL = "預約設置失敗";
    public static final String QUERY_SETMEAL_SUCCESS = "查詢套餐數據成功";
    public static final String QUERY_SETMEAL_FAIL = "查詢套餐數據失敗";
    public static final String ROLE_ADD_SUCCESS = "角色新增成功";
    public static final String ROLE_ADD_FAIL = "角色新增失敗";
    public static final String ROLE_EDIT_SUCCESS = "角色編輯成功";
    public static final String ROLE_EDIT_FAIL = "角色編輯失敗";
    public static final String ROLE_DELETE_FAIL = "角色刪除失敗";
    public static final String ROLE_DELETE_SUCCESS = "角色刪除成功";
    public static final String ROLE_QUERY_FAIL = "查詢角色失敗";
    public static final String ROLE_QUERY_SUCCESS = "查詢角色成功";
    public static final String PERMISSION_QUERY_FAIL = "查詢權限失敗";
    public static final String PERMISSION_QUERY_SUCCESS = "查詢權限成功";
    public static final String PERMISSION_ADD_FAIL = "新增權限失敗";
    public static final String PERMISSION_ADD_SUCCESS = "新增權限成功";
    public static final String PERMISSION_EDIT_FAIL = "編輯權限失敗";
    public static final String PERMISSION_EDIT_SUCCESS = "編輯權限成功";
    public static final String PERMISSION_DELETE_FAIL = "刪除權限失敗";
    public static final String PERMISSION_DELETE_SUCCESS = "刪除權限成功";
    public static final String MEMBER_QUERY_FAIL = "查詢會員失敗";
    public static final String MEMBER_QUERY_SUCCESS = "查詢會員成功";

    public static final Object MEMBER_ADD_FAIL = "新增會員失敗";
    public static final String MEMBER_ADD_SUCCESS = "新增會員成功";
    public static final String MEMBER_EDIT_FAIL = "編輯會員失敗";
    public static final String MEMBER_EDIT_SUCCESS = "編輯會員成功";
    public static final String MEMBER_DELETE_FAIL = "刪除會員失敗";
    public static final String MEMBER_DELETE_SUCCESS = "刪除會員成功";
    public static final String GET_MEMBER_NUMBER_REPORT_SUCCESS = "取得會員數量報表成功";
    public static final String GET_SETMEAL_COUNT_REPORT_SUCCESS = "取得套餐數量報表成功";
    public static final String GET_SETMEAL_COUNT_REPORT_FAIL = "取得套餐數量報表失敗";
    public static final String GET_BUSINESS_REPORT_FAIL = "取得營業報表失敗";
    public static final String GET_BUSINESS_REPORT_SUCCESS = "取得營業報表成功";
    public static final String ADD_MENU_SUCCESS = "新增菜單成功";
    public static final String ADD_MENU_FAIL = "新增菜單失敗";
    public static final String EDIT_MENU_SUCCESS = "編輯菜單成功";
    public static final String EDIT_MENU_FAIL = "編輯菜單失敗";
    public static final String DELETE_MENU_SUCCESS = "刪除菜單成功";
    public static final String DELETE_MENU_FAIL = "刪除菜單失敗";
    public static final String QUERY_MENU_SUCCESS = "查詢菜單成功";
    public static final String QUERY_MENU_FAIL = "查詢菜單失敗";
    public static final Object QUERY_ORDER_FAIL = "查詢訂單失敗";
    public static final String QUERY_ORDER_SUCCESS = "查詢訂單成功";
    public static final String ORDER_ADD_FAIL = "新增訂單失敗";
    public static final String ORDER_ADD_SUCCESS = "新增訂單成功";
    public static final String ORDER_EDIT_FAIL = "編輯訂單失敗";
    public static final String ORDER_EDIT_SUCCESS = "編輯訂單成功";
    public static final String ORDER_DELETE_FAIL = "刪除訂單失敗";
    public static final String ORDER_DELETE_SUCCESS = "刪除訂單成功";
    public static final String GET_MEMBER_HEALTH_REPORT_SUCCESS = "取得個人健康報表成功";
    public static final String GET_MEMBER_HEALTH_REPORT_FAIL = "取得個人健康報表失敗";
    public static final String INSERT_MEMBER_HEALTH_STATUS_SUCCESS = "新增個人健康狀態成功";
    public static final String INSERT_MEMBER_HEALTH_STATUS_FAIL = "新增個人健康狀態失敗";
    public static final String QUERY_MEMBER_SUCCESS = "查詢會員成功";
    public static final String QUERY_MEMBER_FAIL = "查詢會員失敗";
}
