dubbo:
  application:
    name: health_backend
  registry:
    address: zookeeper://localhost:2181
  consumer:
    check: false
  config-center:
    timeout: 60000
  scan:
    base-packages: com.timmy.health.controller



