gmail:
  address: "examyou076@gmail.com"
#spring setting
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/health?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: timmy072869
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.MultipartAutoConfiguration
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  #redis setting
  redis:
    password: timmy0728
    host: 192.168.37.133
    port: 6379
    client-type: lettuce
    connect-timeout: 30000
    lettuce:
      pool:
        enabled: true
  mail:
    host: smtp.gmail.com
    username: examyou076@gmail.com
    password: yaiiow159
    properties:
      mail:
        ssl:
          enable: true
server:
  port: 82
# dubbo setting
dubbo:
  application:
    name: health_backend
  registry:
    address: zookeeper://192.168.37.133
    port: 2181
  consumer:
    check: false
  config-center:
    timeout: 60000
  scan:
    base-packages: com.timmy.health.controller






